<?php


/**
 * Description of Constants
 *
 * @author bfan
 */
interface IConstants
{

    /**
     * Global Debug tag
     */
    const _DEBUG = False;
//    const _DEBUG = TRUE;

    /**
     * Database.inc
     */
    const DB_HOST = "localhost";
    const DB_USERID = "root";
    const DB_PASSWORD = "bobosoft";
    const DB_NAME = "esp8266";
//    const DB_HOST = "";
//    const DB_USERID = "";
//    const DB_PASSWORD = "";
//    const DB_NAME = "";


    /* All table */
    const DBCOL_ID_INSERT = "ID";
    const TABLENAME_STATE = "esp8266";

    /* table state */
    const DBCOL_STATE_1 = "state1";

    
    
    
    
    
    /**
     * Login.inc
     */
//    const LOGIN_USERNAME = "username";
//    const LOGIN_PASSWORD = "password";
//    const DBCOL_LOGIN_USERNAME = "username";
//    const DBCOL_LOGIN_PASSWORD_HASHED = "hashedPassword";
//    const LOGIN_PAGE = "util/login/login.php";
//    const LOGIN_REDIRECT_PAGE = "../../admin_console.php";

}
